### ISSUE TITLE
Difficulty modifying and executing imports in code via stanford_capx_sync_importer() & hook_entity_alter()

### ISSUE THREAD

**Issue by ghost** [SU-SWS/stanford_capx#151]
[capx_implementation.txt](https://github.com/SU-SWS/stanford_capx/files/1349516/capx_implementation.txt)
Tagging @sherakama per Zach.

I'm attempting to synchronize individual accounts' user profiles on first login via SUNet, and to synchronize a custom group of SUNet IDs, defined dynamically, on cron. I have not discovered a wrapper function in the CAPx module to directly call the API, and so have configured importers in the GUI which I am attempting to manually call and alter configuration via hook_entity_alter().

I'm calling a mapper / importer via `stanford_capx_sync_importer("my_importer_machine_name")`, then using `hook_entity_alter($entities, $type)` to sort through config entities of type "capx_cfe" to inject a dynamically indicated single SUNet, or a coma delimited list of SUNets into `$entity->sunet_id`.

When inspected, the config entity appears to be properly structured with the new SUNet IDs. The manually initiated & configured import works at times, and doesn't others.

I have discovered that the import seems to be somewhat reliant on the CRON settings established for it via the GUI. Perhaps the import isn't running if it has already been run within the time window established via the importer's CRON settings?

Is there a way to run the importer regardless of those settings? The use case is that I'm attempting to run the same importer "single_user_custom" or whatever, each time a user logs in for the first time. Each time the importer is run, I inject the appropriate SUNet via hook_entity_alter.

So far it appears failure is always accompanied by the watchdog log "'Etag matched. No processing happened." Although I'm not certain how related this is.

I've attached the code I'm using to call the importer and interact with the configuration entity.

**Comment by sherakama** [comment]
Hey Eric,

Thanks for reaching out. I'll start off with some documentation: https://github.com/SU-SWS/stanford_capx/tree/7.x-3.x/includes/CAPx/APILib

^ This PHP library is what handles the communication between the CAPx module and the API. You can use it to hit any of the available endpoints with the appropriate parameters and get nicely packaged data back. Most of those API functions pass through to the https://github.com/SU-SWS/stanford_capx/blob/7.x-3.x/includes/CAPx/APILib/AbstractAPILib.php#L185 method.

`etag`s are an identifier from the API if something has changed since the last time the module tried to import a person's profile. So that error message you are receiving is letting you know that you have successfully connected with the API, fetched profile information, and compared the locally stored etag to the API's response etag. If they match the module skips over trying to update the local entity (profile, user, etc) as there shouldn't be anything new to grab.

> to synchronize a custom group of SUNet IDs, dynamically, on cron. 

This sounds like an interesting use case that I am surprised we have yet to tackle. To accomplish this you still need both an importer and a mapper. You can create both of these things through the UI and I would recommend doing so. For extra points I would also recommend exporting them to your custom module so that they are bundled with this functionality. 

Here is a small code block that hopefully can get you on your way. Instead of trying to alter the entity on load you can, in the user_login hook, deliberately load the EntityImporter and change its settings using the library objects and exposed public functions.
 
```
// Replace this array with your list from the authmap table.
$my_sunets = ['sheamck', 'rvogl']; 

// Load up the entity importer that you have already created.
$importer = CAPxImporter::loadEntityImporter('demo_importer');

// Get the configuration options from the object.
$config = $importer->getOptions();

// Replace the sunet_id list with your dynamic list. Has to be a string. 
$config['sunet_id'] = implode(",", $my_sunets);

// Set the config options back to the object.
$importer->addOptions($config);

// Run the importer without creating a batch or checking for cron timestamp. 
// Please be careful with this function as long lists of sunets can cause the
// remote API server to time out and not send back any results. 
$importer->justDoIt();
```

I hope this helps.

Cheers,
Shea

**Comment by ghost** [comment]
Thanks very much, I'll look into the docs you linked. I believe the example code you provided will solve my most pressing use case ($importer->justDoIt() with a single sunet).

Much appreciated.
