### ISSUE TITLE
Images not pulled from CAP

### ISSUE THREAD

**Issue by labbydev** [SU-SWS/stanford_capx#61]
I have set up my mapping trying to pull in the profile photo from CAP. I have tried using `$.profilePhotos`, `$.profilePhotos.bigger` and `$.profilePhotos.big` but none of them appear to be pulling in the image. Has there been a change in the naming conventions for the profile photo?

For reference this is the profile I've been using to test - https://profiles.stanford.edu/jia-wang?releaseVersion=6.40.7 Since there is a photo in CAP I assume that it should be pulling in the same image into my site.

**Comment by sherakama** [comment]
Hello @labbydev,

I checked with the API and it does look like JIA has a profile image and the data is present in the API. What type of field are you trying to pull this data in to? The JSON paths `$.profilePhotos.bigger` and `$.profilePhotos.big` are valid for an image field. If you are looking to grab just the URL for a text field you can use something like: `$.profilePhotos.bigger.url`.

I would look at the watchdog logs for some helpful debugging information. In there it should give you a hint to what the issue is. It could be that the field type is incompatible or that the system was unable to write the file to the disk.

**Comment by labbydev** [comment]
I am trying to pull it into an image field

**Comment by sherakama** [comment]
I am guessing you were able to resolve this issue as it is now closed. Do you mind letting me know what the issue was and how you discovered how to resolve it? I would like to have your feedback on the troubleshooting of mapping paths.

**Comment by labbydev** [comment]
There were a series of permissions issues that required resolving.

**Comment by sherakama** [comment]
Thank you for letting me know.
